{{- if .Values.secrets.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secrets.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secrets.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.secrets.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.secrets.existingSecret }}
    creationPolicy: Owner
  data:
    {{- range .Values.secrets.externalSecret.data }}
    - secretKey: {{ .name }}
      remoteRef:
        key: {{ .key }}
    {{- end }}
{{- end }}
